version: "3.9"
services:
  app:
    build:
      context: .
    container_name: outpostapp
    # docker build -t outpostapp .
    #image: outpostapp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      # - POSTGRES_DB: ${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
      POSTGRES_HOST: db
    volumes:
      - .:/app
      - /node_modules
    working_dir: /app
    ports:
      - 3000:3000
    restart: always
  db:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_PASSWORD: example
      #POSTGRES_USER: ${POSTGRES_USER}
      #POSTGRES_DB: ${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    restart: always
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always
