version: "3.9"
services:
  app:
    image: outpostapp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWD: example
      POSTGRES_HOST: db
    ports:
      - 3000:3000
  db:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_PASSWORD: example
