default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: postgresql://localhost/outpost_development
  username: outpost
  password: password
test:
  <<: *default
  url: postgresql://localhost/outpost_test
  username: outpost
  password: password
production:
  <<: *default
  database: outpost_production
  username: outpost
  password: <%= ENV['OUTPOST_DATABASE_PASSWORD'] %>
